name: KayitAsistani
main: com.kayitasistani.KayitAsistani
version: 1.0
api-version: 1.20
commands:
  kayıt:
    description: Kayıt olma komutu
    usage: /kayıt <şifre>
    permission: kayitasistani.kayit
  giriş:
    description: Giriş yapma komutu
    usage: /giriş <şifre>
    permission: kayitasistani.giris
  şifre-değiştir:
    description: Şifre değiştirme komutu
    usage: /şifre-değiştir <eski_şifre> <yeni_şifre>
    permission: kayitasistani.sifredegistir
  arkadaş-ekle:
    description: Arkadaş ekleme komutu
    usage: /arkadaş-ekle <kullanıcı>
    permission: kayitasistani.arkadasekle
permissions:
  kayitasistani.kayit:
    description: Kayıt olma izni
    default: true
  kayitasistani.giris:
    description: Giriş yapma izni
    default: true
  kayitasistani.sifredegistir:
    description: Şifre değiştirme izni
    default: true
  kayitasistani.arkadasekle:
    description: Arkadaş ekleme izni
    default: true 