name: KayitAsistani
main: com.kayitasistani.KayitAsistani
version: 1.0
api-version: 1.20
commands:
  kayıt:
    description: Kayıt olma komutu
    usage: /kayıt <şifre>
    permission: kayitasistani.kayit
  giriş:
    description: Giriş yapma komutu
    usage: /giriş <şifre>
    permission: kayitasistani.giris
  şifremideğiştir:
    description: Şifrenizi değiştirir
    usage: /şifremideğiştir <eskişifre> <yenişifre>
    permission: kayitasistani.sifremidegistir
  profil:
    description: Hesap bilgilerinizi ve istatistiklerinizi gösterir
    usage: /profil
    permission: kayitasistani.profil
permissions:
  kayitasistani.kayit:
    description: Kayıt olma izni
    default: true
  kayitasistani.giris:
    description: Giriş yapma izni
    default: true
  kayitasistani.sifremidegistir:
    description: Şifre değiştirme izni
    default: true
  kayitasistani.profil:
    description: Profil görüntüleme izni
    default: true